services:
  postgres:
    image: postgres:latest
    container_name: onepenny-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: onepenny2507031357
      POSTGRES_DB: onepenny
    ports:
      - "5432:5432"
    volumes:
      - onepenny_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: onepenny-redis
    ports:
      - "6379:6379"
    volumes:
      - onepenny_redis_data:/data

volumes:
  onepenny_pg_data:
  onepenny_redis_data: